["protostar.config"]
protostar_version = "0.2.3"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
index = [
    "./src/Index.cairo",
]

index_factory = [
    "./src/index_factory.cairo",
]

lending_module = [
    "./src/modules/strategy_module.cairo",
]

strategy_registry = [
    "./src/strategy_registry.cairo",
]

module_registry = [
    "./src/module_registry.cairo",
]