["protostar.config"]
protostar_version = "0.3.2"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
index = [
    "./src/Index.cairo",
]

index_factory = [
    "./src/index_factory.cairo",
]

lending_module = [
    "./src/modules/strategy_module.cairo",
]

ERC4626_strategy = [
    "./src/strategies/ERC4626_strategy.cairo",
]

strategy_registry = [
    "./src/strategy_registry.cairo",
]

index_registry = [
    "./src/index_registry.cairo",
]

module_registry = [
    "./src/module_registry.cairo",
]

ERC4626 = [
    "./src/yagi/erc4626/ERC4626.cairo",
]