["protostar.config"]
protostar_version = "0.2.3"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
index = [
    "./contracts/Index.cairo",
]

lending_module = [
    "./contracts/modules/strategy_module.cairo",
]